### ISSUE TITLE
Redirect does not work

### ISSUE THREAD

**Issue by pandurx** [tbs-sct/gcconnex#100]
Link from document/email directs user back to the main page after login
Transferred from Leankit cards T199 and T241

**Comment by bart-j** [comment]
Same problems as Christine, finding it hard to reproduce the bug (but curious we reported it both). The problem seems to be restricted to specific content types. Found (and fixed) problems with the following content types:
* (Calendar) Events
* Pages
* Polls
* Tasks

I also testes these content types, there the problem does not seem to appear (i.e. the user is redirected back correctly to the content after login):
* Activity
* Groups 
* Blogs
* Bookmarks
* Files
* The Wire
* Photos
