### ISSUE TITLE
Discussion missing access level name

### ISSUE THREAD

**Issue by Troy-Lawson** [tbs-sct/gcconnex#312]
GCCON-236
After creating a discussion in a closed group, I went back to edit the discussion, and the Access level now says "Missing access level name" (see screen shot). 
 The access level should of been automatically been set to the group, as per the default settings (see second screen shot).

**Comment by piet0024** [comment]
This seems to work fine on preprod but not production. I believe the issue was caused with the way users can start a discussion from the quick start discussion box not passing the access level to the form.

The specific file is wet4/views/default/groups/profile/discuss_start
The groups default acl should be passed to the form through that view.
Perhaps that file needs to be updated on prod.
