### ISSUE TITLE
On the Federated Search, GCconnex menu items with drop down menus are not working

### ISSUE THREAD

**Issue by Troy-Lawson** [tbs-sct/gcconnex#332]
GCCON-98
When you are on the "GCconnex" page of the Federated search (http://intranet.canada.ca/search-recherche/query-recherche-eng.aspx?q=&a=s&s=3&chk4=True&wb-srch-sub=), the drop down menus for "Career" and "More" don't work.

**Comment by piet0024** [comment]
This may be caused by a javascript error happening with the wet-boew,js file that handles the drop down. 

Getting: Expected ']' - as an error

I'll keep looking into it.

**Comment by piet0024** [comment]
http://stackoverflow.com/questions/14450688/how-to-convert-an-html-page-to-aspx-page-and-add-remove-controls-to-it-without

It says the doctype on the page should be: 
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

Since the search is an asp version of the html perhaps this needs to be added to the page?

**Comment by pandurx** [comment]
@piet0024 It would be a good idea to inform Rajeev of your findings :+1:

**Comment by pandurx** [comment]
I took a look on both sites, they both have the same <!DOCTYPE html>
