### ISSUE TITLE
Titre n'apparait pas dans une billet partagé sur le fil

### ISSUE THREAD

**Issue by PhilAndrecheck** [tbs-sct/gcconnex#430]
Bonjour!
Lorsque qq'un a partagé mon message sur le fil, le tite n'apparait pas dans le courriel de notification :

This is a system-generated message from GCconnex. Please do not reply to this message | Ceci est un message généré par le système de GCconnex. Veuillez ne pas répondre à ce message 
GCconnex 
(Le français suit)
Kevin Lagacé shared your wire with title '' 
Kevin Lagacé has shared your wire on the wire, to view or reply to this please click on the following link: https://gcconnex.gc.ca/thewire/view/24049587 
Learn more about GCconnex notifications. Need help? Contact us.
To unsubscribe from these notifications, login to GCconnex and edit your notifications' settings.
Kevin Lagacé a partagé votre wire avec le titre '' 
Kevin Lagacé a partagé votre wire sur le fil, pour consulter ou répondre, veuillez cliquer sur le lien suivant : https://gcconnex.gc.ca/thewire/view/24049587 
Apprenez davantage au sujet des notifications de GCconnex. Besoin d’aide? Contactez-nous.
Pour vous désabonner de ces notifications, connectez-vous à GCconnex et modifiez vos paramètres de notifications.
-

**Comment by Steph4104** [comment]
Fix on preprod. Maybe the push of november 12th fix it

**Comment by Phanoix** [comment]
Looks like it's been fixed and the fix is either already on production or will be after next update.

**Comment by LemieuxGen** [comment]
@Phanoix this issue is not fixed. I'm still receiving multiple notifications with no content. for example some have the title, but no description content (and the item on GCconnex actually has content). See example below (sorry attachments are not working):

Sasha.Hansonpastran posted a new discussion entitled Public Management (Bulletin) de la gestion publique - Fall-Automne 2016 
The description of the new posting is: 


View or reply 
You can like, share or subscribe to this content directly in GCconnex

**Comment by Steph4104** [comment]
This bug is related to a blog share on the wire. 
We can create an new issu and add a list of all problem, like when create a new discussion etc...

**Comment by Phanoix** [comment]
We should test this (new discussion notifications) on pre-production, if it's not working properly there either this should be reopened.

**Comment by Steph4104** [comment]
Fix in pull request #486 

@LemieuxGen , do you have other exemple of notification without content or title?
